# Generated by Django 4.1.3 on 2022-11-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=80)),
                ('cname', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
                ('cno', models.IntegerField()),
                ('cin', models.DateTimeField()),
                ('cout', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Hotel Name',
            },
        ),
    ]
