# Generated by Django 4.1.3 on 2022-11-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_management_system', '0002_alter_hotel_cin_alter_hotel_cout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='cin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='cout',
            field=models.DateTimeField(),
        ),
    ]
